# Copyright Contributors to the Open Cluster Management project
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    a: b
  name: fake-deployment
  namespace: fake-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      a: b
  template:
    metadata:
      labels:
        a: b
    spec:
      containers:
      - name: my-container
        image: nginx
        {{- if or (eq .ResourceRequirement.Type "Default") (eq .ResourceRequirement.Type "") }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        {{- end }}
        {{- if eq .ResourceRequirement.Type "BestEffort" }}
        resources: {}
        {{- end }}
        {{- if eq .ResourceRequirement.Type "ResourceRequirement" }}
        resources:
          {{ .ResourceRequirement.ResourceRequirements | indent 10 }}
        {{- end }}
